config/routes.rb
Rails.application.routes.draw do
  resource :session, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create]
  root "portfolios#show"

  resources :posts, path: "blog"

  resource :portfolio, only: [:show]

  resource :about, only: [:show]

  resource :resume, only: [:show, :edit]

end

app/models/page.rb
class Page < ActiveRecord::Base
end

app/models/portfolio.rb
class Portfolio < ActiveRecord::Base
end

app/models/post.rb
class Post < ActiveRecord::Base
  def pretty_time
    self.created_at.in_time_zone(-5).strftime("%m-%d-%Y")
  end
end

app/models/project.rb
class Project < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :email, presence: true, uniqueness: true
  validates :password_digest, presence: true
end

app/controllers/abouts_controller.rb
class AboutsController < ApplicationController
  def show
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Monban::ControllerHelpers
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  def show
    @projects = Project.all
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all.reverse
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    redirect_to root_path
  end

  def post_params
    params.require(:post).permit(:title, :body, :description)
  end
end

app/controllers/resumes_controller.rb
class ResumesController < ApplicationController
  def show
  end

  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :require_login, only: [:new, :create]

  def new
  end

  def create
    user = authenticate_session(session_params)

    if sign_in(user)
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
    sign_out
    redirect_to root_path
  end

  private

  def session_params
    params.require(:session).permit(:email, :password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: [:new, :create]

  def new
    @user = User.new
  end

  def create
    @user = sign_up(user_params)

    if @user.valid?
      sign_in(@user)
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/abouts/show.html.erb
<div class="header">
  <h1><%= link_to "Kiernan", root_path %></h1>
</div>
<div class="navigation">
  <%= render "layouts/navigation" %>
</div>
<div class="about">
  <hr>
  <p>My name is Matt Kiernan.</p>

  <p>I'm a recent graduate of Thoughtbot's Metis program.</p>

  <p>I also have 8 years of integrated marketing experience.</p>

  <p>When not building things, I perform improv and play baseball around Boston.</p>

  <p>You can view my <%= link_to "full resume here", resume_path %>, or contact me at <%= mail_to "matt.kiernan@gmail.com", "matt.kiernan@gmail.com" %></p>
  <hr>
</div>

app/views/layouts/_navigation.html.erb
<ul class="navigation">
  <li><%= link_to "Portfolio", "/portfolio" %></li>
  <li>|</li>
  <li><%= link_to "About", "/about" %></li>
  <li>|</li>
  <li><%= link_to "Resume", "/resume" %></li>
  <li>|</li>
  <li><%= link_to "Blog", "/blog" %></li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<title>KIERNAN</title>
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
<%= csrf_meta_tags %>
<link href='http://fonts.googleapis.com/css?family=Syncopate' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Ubuntu+Mono' rel='stylesheet' type='text/css'>

</head>
<body>
<% if signed_in? %>
  <div class="admin-controls">
  <ul>
    <li><%= link_to "Sign out", session_path, method: :delete %></li>
    <li><%= link_to "New post", new_post_path %></li>
  </ul>
</div>
  <% end %>
<div class="page-content">
    <%= yield %>
  </div>
  <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
     (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
       m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
         })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-59049165-1', 'auto');
    ga('send', 'pageview');

  </script>
</body>
</html>

app/views/portfolios/show.html.erb
<div class="header">
  <h1><%= link_to "Kiernan", root_path %></h1>
</div>
<div class="navigation">
  <%= render "layouts/navigation" %>
</div>
<div class="hero">
  <hr />
  <p>Here's a collection of projects I'm currently working on.
  <p>My personal favorite, <%= link_to "PitchFort", "https://pitchfort.herokuapp.com" %>, is a CRM tool for PR professionals, featuring oauth and CSV uploads.</p>
  <p>I also recommend <%=link_to "SurveyCat", "https://surveycat.herokuapp.com" %>, a simple survey-builder.</p>
  <p>I aim to write loosely coupled code, and enjoy refactoring old
  apps.</p>
  <p>When launching apps, please be patient. All are hosted for free on Heroku
  and require a few moments to load.
  <hr />
</div>
<%= render "refills/grid_items" %>

app/views/posts/_form.html.erb
<%= form_for post do |form| %>
  <div class="form-title">
    <%= form.text_field :title, :class => "form_title", :placeholder => "Title" %>
  </div>
  <div class="form-description">
    <%= form.text_field :description, :class => "form_description", :placeholder => "Description" %>
  </div>
  <div class="form-body">
    <%= form.text_area :body, :class => "form_body", :placeholder => "Body" %>
  </div>
  <div class="submit-button">
    <%= form.submit "Submit", :class => "submit_button" %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<%= link_to post do %>
<div class="post-thumbnail">
  <h4 class="post-title"><%= post.title %></h4>
  <p class="post-description"><%= post.description %>
  <hr>
</div>
<% end %>

app/views/posts/edit.html.erb
<%= render "form", post: @post %>

app/views/posts/index.html.erb
<div class="header">
  <h1><%= link_to "Kiernan", root_path %></h1>
</div>
<div class="navigation">
  <%= render "layouts/navigation" %>
</div>
<%= render @posts %>

app/views/posts/new.html.erb
<h2 class="post-title">New post</h2>

<%= render "form", post: @post %>

app/views/posts/show.html.erb
<div class="header">
  <h1><%= link_to "Kiernan", root_path %></h1>
</div>
<div class="navigation">
  <%= render "layouts/navigation" %>
</div>
<div class="post-title">
  <h2><%= @post.title %></h2>
  <% if signed_in? %>
    <%= link_to "Edit post", edit_post_path(@post) %>
    <%= button_to "Delete post", @post, method: :delete %>
  <% end %>
  <h5><%= @post.pretty_time %></h5>
</div>
<div class="post-body">
  <p><%= @post.body.gsub(/\n/, '<br/>').html_safe %></p>
</div>

app/views/refills/_grid_items.html.erb
<div class="grid-items">
  <a href="https://aqueous-retreat-9817.herokuapp.com/" target="_blank" class="grid-item">
    <img src="/megaphone.png" alt="">
    <h1>Shoutr</h1>
    <p>Keep up to date with friends</p>
  </a>
  <a href="https://pitchfort.herokuapp.com" class="grid-item grid-item-big grid-item-image" target="_blank">
    <img src="/newspaper.png" alt="">
    <h1>PitchFort</h1>
    <p>Track emails to & from journalists</p>
  </a>
  <a href="https://surveycat.herokuapp.com" target="_blank" class="grid-item grid-item-big grid-item-image-2">
    <img src="/survey.png" alt="">
    <h1>SurveyCat</h1>
    <p>Create & take surveys</p>
  </a>
  <a href="http://intense-hollows-7924.herokuapp.com/session/new" target="_blank" class="grid-item" target="_blank">
    <img src="/camera.png" alt="">
    <h1>Pixtr</h1>
    <p>(pending design)</p>
  </a>
  <a href="javascript:void(0)" class="grid-item">
    <img src="/question.png" alt="">
    <h1>Coming Soon</h1>
    <p>Hangman</p>
  </a>
  <a href="https://calm-inlet-7623.herokuapp.com/" target="_blank" class="grid-item">
    <img src="/list.png" alt="">
    <h1>Taskr</h1>
    <p>(pending design)</p>
  </a>
  <a href="javascript:void(0)" class="grid-item">
    <img src="/shortener.png" alt="">
    <h1>Coming Soon</h1>
    <p>Shortnr</p>
  </a>
</div>

app/views/refills/_navigation.html.erb
<header class="navigation">
  <div class="menu-wrapper">
    <a href="javascript:void(0)" class="logo">
      <img src="https://raw.github.com/Magnus-G/Random/master/placeholder_logo_1.png" alt="">
    </a>
    <p class="navigation-menu-button" id="js-mobile-menu">MENU</p>
    <div class="nav">
      <ul id="navigation-menu">
        <li class="nav-link"><a href="javascript:void(0)">Products</a></li>
        <li class="nav-link"><a href="javascript:void(0)">About Us</a></li>
        <li class="nav-link"><a href="javascript:void(0)">Contact</a></li>
        <li class="nav-link more"><a href="javascript:void(0)">More</a>
          <ul class="submenu">
            <li><a href="javascript:void(0)">Submenu Item</a></li>
            <li><a href="javascript:void(0)">Another Item</a></li>
          </ul>
        </li>
        
      </ul>
    </div>
    <div class="navigation-tools">
      <div class="search-bar">
        <div class="search-and-submit">
          <input type="search" placeholder="Enter Search" />
          <button type="submit">
            <img src="https://raw.githubusercontent.com/Magnus-G/Random/master/search-icon.png" alt="">
          </button>
        </div>
      </div>
      <a href="javascript:void(0)" class="sign-up">Sign Up</a>
    </div>
  </div>
</header>

<script>
  $(function() {
    var menu = $('#navigation-menu');
    var menuToggle = $('#js-mobile-menu');
    var signUp = $('.sign-up');

    $(menuToggle).on('click', function(e) {
      e.preventDefault();
      menu.slideToggle(function(){
        if(menu.is(':hidden')) {
          menu.removeAttr('style');
        }
      });
    });

    // underline under the active nav item
    $(".nav .nav-link").click(function() {
      $(".nav .nav-link").each(function() {
        $(this).removeClass("active-nav-item");
      });
      $(this).addClass("active-nav-item"); 
      $(".nav .more").removeClass("active-nav-item");
    });
  });
</script>

app/views/resumes/show.html.erb
<div class="resume">
  <table>
    <tr class="section">
      <td class="description">
      </td>
      <td class="contact">
        <h1 class="title">MATT KIERNAN</h1>
        <p class="sub-title">Marketer / Product Manager / Web Developer</p>
      </td>
    </tr>
    <tr class="section">
      <td class="description">
        <h6>Contact</h6>
      </td>
      <td class="content contact">
        <p>Email: <%= mail_to "matt.kiernan@gmail.com", "matt.kiernan@gmail.com",
          target: "_blank" %></p>
          <p>Website: <%= link_to "mattkiernan.com", "http://www.mattkiernan.com",
            target: "_blank" %></p>
            <p>GitHub: <%= link_to "github.com/mattkiernan",
              "http://www.github.com/mattkiernan", target: "_blank" %></p>
            </td>
          </tr>
          <tr class="spacer">
            <td></td>
          </tr>
          <tr class="section">
            <td class="description">
              <h6>Summary</h6>
            </td>
            <td class="content">
              <p>I'm a marketer, product manager and full stack web developer
              helping companies launch new products and businesses.</p>
              <p>I have over 9 years of experience managing cross-functional
              teams, budgets & deadlines.</p>
              <p>My recent personal projects include a
              <%= link_to "public relations CRM", "https://pitchfort.herokuapp.com/",
                target:"_blank" %> and an <%= link_to "easy-to-use survey app",
                "https://surveycat.herokuapp.com/", target:"_blank" %>.</p>
                <p>I also teach at <%= link_to "General Assembly",
                  "https://generalassemb.ly/instructors/matt-kiernan/4164",
                  target: "_blank" %> and <%= link_to "perform improv",
                  "http://instagram.com/p/nox-MxqRm2/", target: "_blank" %>
                around Boston.</p>
                </td>
              </tr>
              <tr class="spacer">
                <td></td>
              </tr>
              <tr class="section">
                <td class="description">
                  <h6>Projects & Technical Skills</h6>
                </td>
                <td class="content">
                  <p>Here's a sample of my recent projects, built with <span class="bold">
                    Ruby on Rails & jquery, hosted on heroku and styled with CSS and the
                    <%= link_to "Neat framework", "http://neat.bourbon.io/",
                      target: "_blank" %>.</span></p>
                    <p><%= link_to "Pitchfort",
                      "http://pitchfort.herokuapp.com", target:"_none" %>: A public relations CRM
                    using <span class="bold">Oauth 2 and the Gmail API</span>.
                    <p><%= link_to "SurveyCat",
                    "http://surveycat.herokuapp.com", target:"_blank" %>: An easy-to-use survey tool
                  using <span class="bold">nested attributes.</span></p>
                  <p><%= link_to "Shoutr",
                    "https://aqueous-retreat-9817.herokuapp.com/", target:"_blank" %>
                : A basic micro-blogging app
                  featuring some <span class="bold">polymorphism.</span></p>
                </td>
              </tr>
              <tr class="spacer">
                <td></td>
              </tr>
              <tr>
                <td class="description">
                  <h6>Experience</h6>
                </td>
                <td class="content">
                  <table class="section-header">
                    <tr>
                      <td class="company">KIERNAN | Proprietor</td>
                      <td class="date">June 2014 - Present</td>
                    </tr>
                  </table>
                  <p>Helping organizations launch new products and businesses through web development, marketing campaigns and data analysis.</p>
                  <ul>
                    <li>Designed & launched product marketing efforts for mobile POS startup, ToastPOS.</li>
                    <li>Produced content marketing for OwnerIQ’s programmatic ad-targeting platform.</li>
                    <li>Built custom SQL-based reporting tool for sweetgreen, providing insights into customer purchase behavior.</li>
                  </ul>
                </td>
              </tr>
              <tr>
                <td class="description">
                </td>
                <td class="content">
                  <table class="section-header">
                    <tr>
                      <td class="company"><%= link_to "LevelUp",
                        "http://www.thelevelup.com", target: "_blank" %> |
                        Head of Marketing</td>
                      <td class="date">October 2010 - June 2014</td>
                    </tr>
                  </table>
                  <p>Planned, developed & executed LevelUp’s comprehensive go-to-market
                  strategy, including:</p>
                  <ul>
                    <li>Fully integrated lead generation marketing strategy including display,
                    SEO, SEM, content marketing, re-marketing, email marketing & PR.</li>
                    <li>Fully integrated end-user acquisition marketing strategy including
                    radio, OOH, display & email marketing.</li>

                    <p>Lead marketing & product initiatives, including:</p>
                    <ul>
                    <li>Development of new marketing-related product features.</li>
                    <li>Management of nine  marketing managers while launching seven new markets.</li>
                    <li>The execution of all PR efforts, from story development
                    to drafting releases, pitching reporters and giving interviews.</li>
                    <li>Establishing and executing CRM & marketing automation strategies for
                    identifying new sales leads and ushering prospective clients through the sales
                    funnel via content marketing and email auto-responder drip campaigns.</li>
                    <li>Regularly architecting and executing database queries in SQL to identify
                    trends in customer purchase behavior.</li>
                  </ul>
                </td>
              </tr>
              <tr>
                <td class="description">
                </td>
                <td class="content">
                  <table class="section-header">
                    <tr>
                      <td class="company"><%= link_to "Mullen", "http://www.mullen.com",
                        target: "_blank" %> | Account Supervisor</td>
                      <td class="date">June 2006 - October 2010</td>
                    </tr>
                  </table>
                  <p>Served as direct point of contact for clients and agency team leader
                  while developing and managing planning & production of:</p>
                  <ul>
                    <li>Multi-million dollar year-long marketing plan for SC Johnson’s Shout
                    Stain Remover, extending across TV, in-store free-standing units,
                    sampling, direct mail, print, social media, FSIs and on-pack
                    creative messaging.</li>
                    <li>Complete overhaul and redesign of two government websites for the Department of Defense.
                    Worked with Information Architect to facilitate prototype user-testing to analyze site experience
                    and influence site content organization.</li>
                    <li>Integrated marketing campaigns for LendingTree.com, including TV advertisements, radio and
                    print while managing client budgets and schedule.</li>
                    <li>Integrated campaign promoting new online tools for Orbitz.com including quick-to-market TV
                    advertisements, animated Captivate videos featured in office elevators, print advertisements and
                    out-of-home advertisements appearing in multiple airports.</li>
                  </ul>
                </td>
              </tr>
              <tr class="spacer">
                <td></td>
              </tr>
              <tr>
                <td class="description">
                  <h6>Education</h6>
                </td>
                <td class="content">
                  <table class="section-header">
                    <tr>
                      <td class="company"><%= link_to "Metis", "http://www.thisismetis.com/ruby-on-rails", target: "_blank" %> | Web Developer</td>
                      <td class="date">October 2014 - December 2014</td>
                    </tr>
                    <tr>
                      <td class="company"><%= link_to "Bentley University",
                        "http://www.bentley.edu", target: "_blank" %> | Bachelor of Science, Marketing</td>
                      <td class="date">August 2002 - May 2006</td>
                    </tr>
                  </table>
                </tr>
              </table>
            </div>

app/views/users/new.html.erb
<%= form_for @user do |form| %>

  <% if @user.errors.any? %>
    <%= pluralize(@user.errors.count, "error") %> prevented your account from being created:
    <ul>
      <% @user.errors.full_messages.each do |error_message| %>
        <li><%= error_message %></li>
      <% end %>
    </ul>
  <% end %>

  <div>
    <%= form.label :email %>
    <%= form.email_field :email %>
  </div>
  <div>
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>
  <div>
    <%= form.submit "Sign up" %>
  </div>
<% end %>